{% set version = "0.5.4" %}

package:
  name: jsf
  version: {{ version }}

source:
  - fn: LICENSE-MIT-jsf-{{ version }}
    url: https://raw.githubusercontent.com/ghandic/jsf/{{ version }}/LICENSE
    sha256: 8bf4000731037655e16fe941d3f174f978b3d05b1257d6ae7626cddaa90e5473
  - url: https://pypi.io/packages/source/j/jsf/jsf-{{ version }}.tar.gz
    sha256: ac1d157bb6367c5cc956a8e58217a5b8d5bf04038fe237f218516beed91d4a69

build:
  entry_points:
    - jsf=jsf.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - faker
    - jsonschema
    - pydantic
    - python >=3.7
    - rstr
    - smart_open
    - typer

test:
  imports:
    - jsf
  commands:
    - pip check
    - jsf --help
  requires:
    - pip

about:
  home: https://github.com/ghandic/jsf
  summary: Creates fake JSON files from a JSON schema
  license: MIT
  license_file:
    - LICENSE-MIT-jsf-{{ version }}

extra:
  recipe-maintainers:
    - bollwyvl
