{% set version = "0.5.1" %}

package:
  name: jsf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsf/jsf-{{ version }}.tar.gz
  sha256: e70bc18e80579e8b80969a4cab72a5a8f6926e25cf12054c4fea74d2639a7cc6
  patches:
    - 0000-setup-py-utf8.patch

build:
  entry_points:
    - jsf=jsf.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - faker
    - jsonschema
    - pydantic
    - python >=3.7
    - rstr
    - smart_open
    - typer

test:
  imports:
    - jsf
  commands:
    - pip check
    - jsf --help
  requires:
    - pip

about:
  home: https://github.com/ghandic/jsf
  summary: Creates fake JSON files from a JSON schema
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
