{% set version = "0.5.2" %}

package:
  name: jsf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsf/jsf-{{ version }}.tar.gz
  sha256: ab07fa4bcce59bc425f37c54e8e9d105d03bd138421d17b177575c1ad77ff48b

build:
  entry_points:
    - jsf=jsf.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - faker
    - jsonschema
    - pydantic
    - python >=3.7
    - rstr
    - smart_open
    - typer

test:
  imports:
    - jsf
  commands:
    - pip check
    - jsf --help
  requires:
    - pip

about:
  home: https://github.com/ghandic/jsf
  summary: Creates fake JSON files from a JSON schema
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
