{% set version = "0.5.3" %}

package:
  name: jsf
  version: {{ version }}

source:
  - fn: LICENSE-MIT-jsf-{{ version }}
    url: https://raw.githubusercontent.com/ghandic/jsf/{{ version }}/LICENSE
    sha256: 4e53ccb08b3ba4d247e6c91ff075bc2c0897cd96b7fb59d05e13a9824d45d5de
  - url: https://pypi.io/packages/source/j/jsf/jsf-{{ version }}.tar.gz
    sha256: 110b6b804dabcd69d64a4e569789bb56770814ded8f1ef28c7bce44c7fe1d35e

build:
  entry_points:
    - jsf=jsf.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - faker
    - jsonschema
    - pydantic
    - python >=3.7
    - rstr
    - smart_open
    - typer

test:
  imports:
    - jsf
  commands:
    - pip check
    - jsf --help
  requires:
    - pip

about:
  home: https://github.com/ghandic/jsf
  summary: Creates fake JSON files from a JSON schema
  license: MIT
  license_file:
    - LICENSE-MIT-jsf-{{ version }}

extra:
  recipe-maintainers:
    - bollwyvl
