{% set min_python = "python >=3.8" %}
{% set min_python = "python >=3.8" %}
{% set version = "0.11.2" %}
{% set min_python = "python >=3.8" %}

package:
  name: jsf
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jsf/jsf-{{ version }}.tar.gz
  sha256: 07055b363281d38ce871a9256a00587d8472802c5108721a7fe5884465104b5d

build:
  noarch: python
  number: 1

requirements:
  host:
    - {{ min_python }}
  run:
    - {{ min_python }}

outputs:
  - name: jsf
    build:
      entry_points:
        - jsf = jsf.cli:app
      noarch: python
      script:
        - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - {{ min_python }}
        - pip
      run:
        - {{ min_python }}
        - faker >=15.3.4
        - jsonschema >=4.17.3
        - pydantic >=2.0.0
        - rstr >=3.2.0
        - smart-open-with-http >=6.3.0
        - typing_extensions >=4.9.0
    test:
      imports:
        - jsf
      commands:
        - pip check
      requires:
        - pip

  - name: jsf-with-cli
    build:
      noarch: python
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage('jsf', exact=True) }}
        - typer >=0.7.0
    test:
      requires:
        - pip
        - pytest-cov
        - pyjwt
        - python {{ python_min }}
      commands:
        - pip check
        - jsf --help
        - pytest -vv --pyargs jsf --cov=jsf --cov=branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=99

about:
  home: https://github.com/ghandic/jsf
  summary: Creates fake JSON files from a JSON schema
  license: MIT
  license_file:
    - jsf/LICENSE

extra:
  feedstock-name: jsf
  recipe-maintainers:
    - bollwyvl
