{% set version = "0.7.0" %}
{% set pytest_args = '--cov-fail-under=99' %}

package:
  name: jsf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsf/jsf-{{ version }}.tar.gz
  sha256: 5001c270a641369baa66976d8d050a1cd0d2b352efc0d03d5ae7719efaa6dbc2

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
  run:
    - python >=3.7

outputs:
  - name: jsf
    build:
      entry_points:
        - jsf = jsf.cli:app
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - faker
        - jsonschema >=4.17.3
        - pydantic >=1.10.4
        - python >=3.7
        - requests
        - rstr >=3.2.0
        - smart_open >=6.3.0
    test:
      imports:
        - jsf
      commands:
        - pip check
      requires:
        - pip

  - name: jsf-with-cli
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage('jsf', exact=True) }}
        - typer >=0.7.0
    test:
      requires:
        - pip
        - pytest-cov
        - pyjwt
      commands:
        - pip check
        - jsf --help
        - pytest -vv --pyargs jsf --cov=jsf --cov-report=term-missing:skip-covered --no-cov-on-fail {{ pytest_args }}

about:
  home: https://github.com/ghandic/jsf
  summary: Creates fake JSON files from a JSON schema
  license: MIT
  license_file:
    - jsf/LICENSE

extra:
  feedstock-name: jsf
  recipe-maintainers:
    - bollwyvl
